# Generated by Django 4.1.2 on 2022-11-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
